Traceback (most recent call last):
  File "/home/lucas/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/lucas/.local/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/lucas/.local/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/lucas/.local/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/lucas/.local/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/lucas/.local/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/lucas/.local/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# ver quantidade maxima de linhas e colunas que s√£o exibidas por padr√£o
qtd_cols_padrao = pd.options.display.max_columns
qtd_rows_padrao = pd.options.display.max_rows
print('quantidade m√°xima de linhas exibidas por padr√£o: '+str(qtd_rows_padrao))
print('quantidade m√°xima de colunas exibidas por padr√£o: '+str(qtd_cols_padrao))

# configurar o pandas para mostrar todas as colunas em todos os dataframes
pd.set_option('display.max_columns', None)
# ou
pd.options.display.max_columns = None

# retornar o padr√£o √† quantidade inicial
# pd.options.display.max_columns = qtd_cols_padrao
d.set_option('display.max_columns', qtd_cols_padrao)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_824766/4162632937.py[0m in [0;36m<cell line: 14>[0;34m()[0m
[1;32m     12[0m [0;31m# retornar o padr√£o √† quantidade inicial[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     13[0m [0;31m# pd.options.display.max_columns = qtd_cols_padrao[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 14[0;31m [0md[0m[0;34m.[0m[0mset_option[0m[0;34m([0m[0;34m'display.max_columns'[0m[0;34m,[0m [0mqtd_cols_padrao[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'd' is not defined
NameError: name 'd' is not defined

